### ISSUE TITLE
demo.py报错chunk.choices[0].delta.content list index out of range

### ISSUE THREAD

**Issue by YKYsia** [chatanywhere/GPT_API_free#238]
pycharm代码运行demo.py
使用gpt_35_api_stream(message)进行流式传输调用时，报错：

```
Traceback (most recent call last):
  File "D:\LaTeX\texstudio\Macro\demo.py", line 41, in <module>
    gpt_35_api_stream(messages)
  File "D:\LaTeX\texstudio\Macro\demo.py", line 33, in gpt_35_api_stream
    if chunk.choices[0].delta.content is not None:
       ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

使用gpt_35_api(message)进行非流式传输调用时则正常。
python版本3.12，openai库版本1.13.1

**Comment by chatanywhere** [comment]
已修复该问题
