### ISSUE TITLE
代码中设置了baseUrl和API key后，404报错

### ISSUE THREAD

**Issue by QingjiaTsang** [chatanywhere/GPT_API_free#258]
<img width="618" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/39949421/f67a88a8-94e7-43dd-a7b5-b0b9a2ac91f1">

报错信息：
NotFoundError: 404 <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at APIError.generate (webpack-internal:///(rsc)/./node_modules/.pnpm/openai@4.49.0/node_modules/openai/error.mjs:67:20)
    at OpenAI.makeStatusError (webpack-internal:///(rsc)/./node_modules/.pnpm/openai@4.49.0/node_modules/openai/core.mjs:292:65)
    at OpenAI.makeRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/openai@4.49.0/node_modules/openai/core.mjs:335:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getEmbedding (webpack-internal:///(rsc)/./src/lib/openai.ts:19:22)
    at async POST (webpack-internal:///(rsc)/./src/app/api/notes/route.ts:76:27)
    at async /Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53446
    at async e_.execute (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:44747)
    at async e_.handle (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54700)
    at async doRender (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/base-server.js:1962:32)
    at async DevServer.pipeImpl (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/tsang/Desktop/nextjs-note-taking-chatbot/node_modules/.pnpm/next@14.2.3_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/server/lib/start-server.js:141:13) {
  status: 404,
  headers: {
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '89845fa84ca11d6b-NRT',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'text/html',
    date: 'Sun, 23 Jun 2024 12:10:13 GMT',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=5qa0EilJ4FB618xO2w4FFk4g48pt3hL%2BGpu4GGkjWHIGS67T9ttq03HbG8LoWsUsqOPlCXXV5rWXsOKF1Pp8bq00BKHcVlprlcBhEV%2Bg0W3l5J4FIYy0q3DHUByBb2opkV6pYCA2"}],"group":"cf-nel","max_age":604800}',
    server: 'cloudflare',
    'transfer-encoding': 'chunked'
  },
  request_id: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
 POST /api/notes 500 in 689ms

**Comment by QingjiaTsang** [comment]
baseUrl地址更正为：https://api.chatanywhere.tech/v1
即可
